enum Category {
  Lifestyle
  Health
  Technology
  Music
  Arts
  Education
  Movies
  TV
  Shows
  Sports
  Food
}

type Blog {
  id: ID!
  title: String!
  content: String!
  author: User!
  summary: String
  category: Category!
}

input NewBlogInput{
    title: String!
    content: String!
    summary String
    category: Category!
}
input UpdateBlogInput{
    title: String
    content: String
    summary String
    category: Category
}

# As there are other queries and mutation files
extend type Query {
  blog(id: ID!): Blog!
  blogsByAuthor(author: User!): [Blog]!
  blogsByDate(writtenOn: Date): [Blog]!
}

extend type Mutation {
  newBlog(input: NewBlogInput!): Blog!
  updateBlog(id: ID!, input: UpdateBlogInput): Blog!
  removeBlog(id: ID!): Blog!
}
